### ISSUE TITLE
First step doesn't work

### ISSUE THREAD

**Issue by pierbo** [cormas/cormas#358] opened 2021-03-16 15:21 UTC
A click on the "step" button do nothing

**Comment by hernanmd** [comment] 2021-03-18 22:35
Problem seems to be in CMSpaceView>>timeChanged: method

The #translateTo: of situatedEntitiesViews does not translate any RTElement the first time. This is reproducible checking with the Debugger view.

**Comment by hernanmd** [comment] 2021-08-04 18:08
Fixed in  #424

**Closed by hernanmd** 2021-08-04 18:08 UTC
Labels: bug, priority 1
