### ISSUE TITLE
Instance of CMRehabModel did not understand #theCMRehabManagers

### ISSUE THREAD

**Issue by ElCep** [cormas/cormas#199] opened 2020-07-20 16:01 UTC
I thing some thing wrong append in the last PR. When I tried to load Rehab from the UI an error occur during the inti caused by 
```
initEntities
	"Initialize all the Entity classes of the model"

	"Remove all the PassiveObjects and Located Objects"

	self class passiveClasses
		do: [ :aClass | 
			((aClass inheritsFrom: CMMsg) or: [ aClass isAbstract ])
				ifFalse: [ (aClass inheritsFrom: CMObjectLocation)
						ifTrue: [ (self theEntities: aClass) isNil
								ifFalse: [ (self theEntities: aClass) do: [ :LO | LO leave ] ] ].
					self initializeTheEntity: aClass ] ].	"Remove all the Agents from previous simulation"
	self class socialClasses
		do: [ :aClass | 
			aClass isAbstract
				ifFalse: [ (aClass inheritsFrom: CMAgentLocation)
						ifTrue: [ (self theEntities: aClass) isNil
								ifFalse: [ (self theEntities: aClass) do: [ :LO | LO leave ] ] ].
					self initializeTheEntity: aClass ] ].
	self spaceModel isNil
		ifFalse: [ self spaceModel resetSpatialEntitiesButCells ]
```

**Comment by tomooda** [comment] 2020-07-21 00:03
Fixed by  https://github.com/cormas/cormas/pull/200.
The problem is that the instance variables and accessor methods were based on the old names of entity classes. I found there is a method to automatically generate an instance variable and getter/setter methods, which needed a little fix.
Next time, you can just run `CMYourModel createInstancesAccessorsForAllEntityClasses` to generate those variables and accessors. Yet, you will have to remove old variables and accessors by hand, which is a little hard to do automatically.

**Comment by SergeStinckwich** [comment] 2020-07-21 10:16
Ok, thank you Tomo for the finding about ``createInstancesAccessorsForAllEntityClasses``. Can we imagine calling this method everytime we rename the main class?

**Comment by tomooda** [comment] 2020-07-21 11:10
IMHO, I'd rather use doesNotUnderstand: if performance does not matter.

**Comment by ElCep** [comment] 2020-07-21 15:28
After much discussion with @ChLePage , we think that the accessors are too long if we continue to use this standard. It would be very difficult for us to ask the user to use `theCMECECVegetationUnits` and much easier to use `theVegetationUnits`in `CMECECModel`.

I propose a method (and its test) to find the shortName e.g. #201

**Comment by tomooda** [comment] 2020-07-22 00:52
I sent a PR (https://github.com/ElCep/cormas/pull/12) to the @ElCep 's repository that
* define `shortName` method in the `CMEntity` class
* modify the `getterForEntityClass:` to use the new `shortName`
* add tests for the new `shortName`
* modify each of existing model classes to use the new names generated by the `shortName` method. Yes, we need to modify tons of existing methods to adopt the new naming convention for accessors because `CMAbstractModel` uses the `getterForEntityClass:` method to automatically initialize entity objects and so on.

**Comment by SergeStinckwich** [comment] 2020-07-22 02:01
Thank Tomo, this is great. Why on Etienne repository?

**Comment by tomooda** [comment] 2020-07-22 02:46
Hmm, you are right. I closed the PR to @ElCep 's repo and created a new PR to the cormas repo. (https://github.com/cormas/cormas/pull/202)

**Comment by SergeStinckwich** [comment] 2020-07-22 02:55
Great ! Thank you Tomo.

**Comment by tomooda** [comment] 2020-07-22 03:21
Some tests fail in Pharo 7. Do we need to support Pharo 7? I created a new issue on that. (https://github.com/cormas/cormas/issues/203)

**Comment by ElCep** [comment] 2020-07-22 15:47
I have removed all `theXXXs` getter and accecor in `CMReHabModel` and regenerate them with `CMReHabModel createInstancesAccessorsForAllEntityClasses` in a playground. 
It create all the entities classes but something strange append. 
In rehab we have a class `CMReHabFamily` and the method create accessor as `theFamilies`... where it come from ?

**Comment by tomooda** [comment] 2020-07-22 22:52
`theFamilies` is generated by `'the' , aClass shortName pluralize capitalized`. The `pluralize` method knows some rules of English morphology to answer its plural form. Convenient, isn't it?

**Comment by tomooda** [comment] 2020-07-23 00:01
I found many methods does their own ways of composing the entity gettters/setters, e.g. `'the', aClass name, 's'`. I made a PR to correct those code to use the `CMAbstractModel class>>getterForEntityClass:` and `CMAbstractModel class>>setterForEntityClass:`.

https://github.com/cormas/cormas/pull/214

**Comment by SergeStinckwich** [comment] 2020-07-24 03:38
Close?

**Closed** 2020-07-25 06:33 UTC
Labels: bug
